repository_type: pipeline
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-mettannotator_logo_light.png
    - docs/images/nf-core-mettannotator_logo_light.png
    - docs/images/nf-core-mettannotator_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - conf/test_full.config
    - docs/output.md
    - docs/README.md
    - docs/README.md
    - docs/usage.md
    - conf/igenomes.config
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - ci.yml
  files_unchanged:
    - LICENSE
    - CODE_OF_CONDUCT.md
    - assets/nf-core-mettannotator_logo_light.png
    - docs/images/nf-core-mettannotator_logo_light.png
    - docs/images/nf-core-mettannotator_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  nextflow_config: False
    - params.custom_config_version
    - params.custom_config_base
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
