repository_type: pipeline
org_path: ebi-metagenomics
template:
  prefix: ebi-metagenomics
    - github_badges
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - CHANGELOG.md
    - assets/nf-core-mettannotator_logo_light.png
    - docs/images/nf-core-mettannotator_logo_light.png
    - docs/images/nf-core-mettannotator_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - conf/test_full.config
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - conf/igenomes.config
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/ci.yml
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/NfcoreTemplate.groovy
    - lib/WorkflowMettannotator.groovy
  files_unchanged:
    - LICENSE
    - CODE_OF_CONDUCT.md
    - assets/nf-core-mettannotator_logo_light.png
    - docs/images/nf-core-mettannotator_logo_light.png
    - docs/images/nf-core-mettannotator_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/linting.yml
    - .github/CONTRIBUTING.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .gitignore
  nextflow_config: false
  multiqc_config:
    - report_comment
